#!/usr/bin/env python
# SPDX-License-Identifier: Apache-2.0
"""Compile ``proto/`` into ``src/carla_driver_interface/grpc_api/_proto/``.

The generated modules are committed to the repository so that installing this
package never needs ``grpcio-tools``. ``tests/test_proto_compat.py`` re-runs
this script into a temporary directory and fails if the output drifts.

Two sets of protos are compiled together:

* alpasim's ``egodriver`` contract and what it imports, vendored verbatim under
  ``proto/alpasim_grpc/v0/`` (``proto/README.md`` says from which revision and
  why: ``alpasim-grpc`` requires Python 3.11, Autoware's environment is 3.10);
* this project's extension, ``proto/driver_extension/v0/``.

``protoc`` emits absolute imports (``from alpasim_grpc.v0 import x_pb2``) that
only resolve with the generated tree on ``sys.path``, and a top-level
``alpasim_grpc`` package of ours would collide with the real one wherever both
are installed. So the modules are flattened into one package directory and
their cross-imports rewritten to relative ones. The descriptors keep their
``alpasim_grpc/v0/*.proto`` names, which is what keeps the wire format
upstream's. Another copy of the same revision (``alpasim_grpc``'s own, the
scenario framework's) loads beside it, protobuf sharing identical files; a
different revision would clash.
"""

from __future__ import annotations

import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
PROTO_ROOT = REPO_ROOT / "proto"
OUT_ROOT = REPO_ROOT / "src" / "carla_driver_interface" / "grpc_api" / "_proto"
PROTO_FILES = (
    "alpasim_grpc/v0/common.proto",
    "alpasim_grpc/v0/sensorsim.proto",
    "alpasim_grpc/v0/egodriver.proto",
    "alpasim_grpc/v0/runtime.proto",
    "driver_extension/v0/driver_extension.proto",
)
#: The one proto declaring a service, the only one gRPC stubs are made for.
SERVICE_PROTO = "alpasim_grpc/v0/egodriver.proto"

_ABSOLUTE_IMPORT = re.compile(
    r"^from (?:alpasim_grpc|driver_extension)\.v0 import ", flags=re.MULTILINE
)
_HEADER = (
    "# Generated by scripts/compile_protos.py -- do not edit.\n"
    "# alpasim_grpc/v0/*.proto: NVlabs/alpasim, vendored (Apache-2.0); see proto/README.md.\n"
)


def compile_protos(out_root: Path | None = None) -> Path:
    """Generate the flattened modules into ``out_root``; returns it."""
    out_root = Path(out_root) if out_root is not None else OUT_ROOT
    with tempfile.TemporaryDirectory() as scratch:
        raw = Path(scratch)
        protoc = [sys.executable, "-m", "grpc_tools.protoc", f"-I{PROTO_ROOT}"]
        subprocess.run(
            [*protoc, f"--python_out={raw}", f"--pyi_out={raw}", *PROTO_FILES],
            check=True,
            cwd=PROTO_ROOT,
        )
        subprocess.run(
            [*protoc, f"--grpc_python_out={raw}", SERVICE_PROTO], check=True, cwd=PROTO_ROOT
        )
        if out_root.exists():
            shutil.rmtree(out_root)
        out_root.mkdir(parents=True)
        for generated in sorted(raw.rglob("*.py*")):
            text = _ABSOLUTE_IMPORT.sub("from . import ", generated.read_text())
            (out_root / generated.name).write_text(_HEADER + text)
    (out_root / "__init__.py").write_text(
        '"""Generated protobuf modules; import them through ``grpc_api``."""\n'
    )
    return out_root


def main() -> None:
    out = compile_protos()
    print(f"Generated protobuf modules under {out}")


if __name__ == "__main__":
    main()
