# Generated by scripts/compile_protos.py -- do not edit.
# alpasim_grpc/v0/*.proto: NVlabs/alpasim, vendored (Apache-2.0); see proto/README.md.
from . import common_pb2 as _common_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from typing import ClassVar as _ClassVar, Iterable as _Iterable, Mapping as _Mapping, Optional as _Optional, Union as _Union

DESCRIPTOR: _descriptor.FileDescriptor

class TimeAggregation(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    TIME_AGGREGATION_UNSPECIFIED: _ClassVar[TimeAggregation]
    TIME_AGGREGATION_MEAN: _ClassVar[TimeAggregation]
    TIME_AGGREGATION_MEDIAN: _ClassVar[TimeAggregation]
    TIME_AGGREGATION_MAX: _ClassVar[TimeAggregation]
    TIME_AGGREGATION_MIN: _ClassVar[TimeAggregation]
    TIME_AGGREGATION_LAST: _ClassVar[TimeAggregation]

class RolloutErrorCode(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    ROLLOUT_ERROR_CODE_NONE: _ClassVar[RolloutErrorCode]
    ROLLOUT_ERROR_CODE_UNSPECIFIED: _ClassVar[RolloutErrorCode]
    ROLLOUT_ERROR_CODE_INVALID_SCENE: _ClassVar[RolloutErrorCode]
TIME_AGGREGATION_UNSPECIFIED: TimeAggregation
TIME_AGGREGATION_MEAN: TimeAggregation
TIME_AGGREGATION_MEDIAN: TimeAggregation
TIME_AGGREGATION_MAX: TimeAggregation
TIME_AGGREGATION_MIN: TimeAggregation
TIME_AGGREGATION_LAST: TimeAggregation
ROLLOUT_ERROR_CODE_NONE: RolloutErrorCode
ROLLOUT_ERROR_CODE_UNSPECIFIED: RolloutErrorCode
ROLLOUT_ERROR_CODE_INVALID_SCENE: RolloutErrorCode

class ScenePrefetchRequest(_message.Message):
    __slots__ = ("scene_id",)
    SCENE_ID_FIELD_NUMBER: _ClassVar[int]
    scene_id: str
    def __init__(self, scene_id: _Optional[str] = ...) -> None: ...

class RolloutSpec(_message.Message):
    __slots__ = ("scenario_id", "nr_rollouts", "session_uuids", "start_time_offset_us")
    SCENARIO_ID_FIELD_NUMBER: _ClassVar[int]
    NR_ROLLOUTS_FIELD_NUMBER: _ClassVar[int]
    SESSION_UUIDS_FIELD_NUMBER: _ClassVar[int]
    START_TIME_OFFSET_US_FIELD_NUMBER: _ClassVar[int]
    scenario_id: str
    nr_rollouts: int
    session_uuids: _containers.RepeatedScalarFieldContainer[str]
    start_time_offset_us: int
    def __init__(self, scenario_id: _Optional[str] = ..., nr_rollouts: _Optional[int] = ..., session_uuids: _Optional[_Iterable[str]] = ..., start_time_offset_us: _Optional[int] = ...) -> None: ...

class SimulationRequest(_message.Message):
    __slots__ = ("available_drivers", "rollout_specs", "n_concurrent_per_driver")
    class DriverAddress(_message.Message):
        __slots__ = ("ip", "port")
        IP_FIELD_NUMBER: _ClassVar[int]
        PORT_FIELD_NUMBER: _ClassVar[int]
        ip: str
        port: int
        def __init__(self, ip: _Optional[str] = ..., port: _Optional[int] = ...) -> None: ...
    AVAILABLE_DRIVERS_FIELD_NUMBER: _ClassVar[int]
    ROLLOUT_SPECS_FIELD_NUMBER: _ClassVar[int]
    N_CONCURRENT_PER_DRIVER_FIELD_NUMBER: _ClassVar[int]
    available_drivers: _containers.RepeatedCompositeFieldContainer[SimulationRequest.DriverAddress]
    rollout_specs: _containers.RepeatedCompositeFieldContainer[RolloutSpec]
    n_concurrent_per_driver: int
    def __init__(self, available_drivers: _Optional[_Iterable[_Union[SimulationRequest.DriverAddress, _Mapping]]] = ..., rollout_specs: _Optional[_Iterable[_Union[RolloutSpec, _Mapping]]] = ..., n_concurrent_per_driver: _Optional[int] = ...) -> None: ...

class SceneMetadata(_message.Message):
    __slots__ = ("version_string", "training_date", "dataset_hash", "uuid", "camera_ids", "lidar_ids", "start_time_us", "end_time_us")
    VERSION_STRING_FIELD_NUMBER: _ClassVar[int]
    TRAINING_DATE_FIELD_NUMBER: _ClassVar[int]
    DATASET_HASH_FIELD_NUMBER: _ClassVar[int]
    UUID_FIELD_NUMBER: _ClassVar[int]
    CAMERA_IDS_FIELD_NUMBER: _ClassVar[int]
    LIDAR_IDS_FIELD_NUMBER: _ClassVar[int]
    START_TIME_US_FIELD_NUMBER: _ClassVar[int]
    END_TIME_US_FIELD_NUMBER: _ClassVar[int]
    version_string: str
    training_date: str
    dataset_hash: str
    uuid: str
    camera_ids: _containers.RepeatedScalarFieldContainer[str]
    lidar_ids: _containers.RepeatedScalarFieldContainer[str]
    start_time_us: int
    end_time_us: int
    def __init__(self, version_string: _Optional[str] = ..., training_date: _Optional[str] = ..., dataset_hash: _Optional[str] = ..., uuid: _Optional[str] = ..., camera_ids: _Optional[_Iterable[str]] = ..., lidar_ids: _Optional[_Iterable[str]] = ..., start_time_us: _Optional[int] = ..., end_time_us: _Optional[int] = ...) -> None: ...

class SceneInfo(_message.Message):
    __slots__ = ("scene_id", "provider_kind", "metadata")
    SCENE_ID_FIELD_NUMBER: _ClassVar[int]
    PROVIDER_KIND_FIELD_NUMBER: _ClassVar[int]
    METADATA_FIELD_NUMBER: _ClassVar[int]
    scene_id: str
    provider_kind: str
    metadata: SceneMetadata
    def __init__(self, scene_id: _Optional[str] = ..., provider_kind: _Optional[str] = ..., metadata: _Optional[_Union[SceneMetadata, _Mapping]] = ...) -> None: ...

class ServiceCapacity(_message.Message):
    __slots__ = ("service_name", "total_capacity", "skipped")
    SERVICE_NAME_FIELD_NUMBER: _ClassVar[int]
    TOTAL_CAPACITY_FIELD_NUMBER: _ClassVar[int]
    SKIPPED_FIELD_NUMBER: _ClassVar[int]
    service_name: str
    total_capacity: int
    skipped: bool
    def __init__(self, service_name: _Optional[str] = ..., total_capacity: _Optional[int] = ..., skipped: bool = ...) -> None: ...

class RuntimeInfo(_message.Message):
    __slots__ = ("max_supported_concurrent_rollouts", "nr_workers", "renderer_type", "scenes", "service_capacities", "runtime_version", "nre_version", "physics_version", "driver_version", "traffic_version", "video_model_version")
    MAX_SUPPORTED_CONCURRENT_ROLLOUTS_FIELD_NUMBER: _ClassVar[int]
    NR_WORKERS_FIELD_NUMBER: _ClassVar[int]
    RENDERER_TYPE_FIELD_NUMBER: _ClassVar[int]
    SCENES_FIELD_NUMBER: _ClassVar[int]
    SERVICE_CAPACITIES_FIELD_NUMBER: _ClassVar[int]
    RUNTIME_VERSION_FIELD_NUMBER: _ClassVar[int]
    NRE_VERSION_FIELD_NUMBER: _ClassVar[int]
    PHYSICS_VERSION_FIELD_NUMBER: _ClassVar[int]
    DRIVER_VERSION_FIELD_NUMBER: _ClassVar[int]
    TRAFFIC_VERSION_FIELD_NUMBER: _ClassVar[int]
    VIDEO_MODEL_VERSION_FIELD_NUMBER: _ClassVar[int]
    max_supported_concurrent_rollouts: int
    nr_workers: int
    renderer_type: str
    scenes: _containers.RepeatedCompositeFieldContainer[SceneInfo]
    service_capacities: _containers.RepeatedCompositeFieldContainer[ServiceCapacity]
    runtime_version: _common_pb2.VersionId
    nre_version: _common_pb2.VersionId
    physics_version: _common_pb2.VersionId
    driver_version: _common_pb2.VersionId
    traffic_version: _common_pb2.VersionId
    video_model_version: _common_pb2.VersionId
    def __init__(self, max_supported_concurrent_rollouts: _Optional[int] = ..., nr_workers: _Optional[int] = ..., renderer_type: _Optional[str] = ..., scenes: _Optional[_Iterable[_Union[SceneInfo, _Mapping]]] = ..., service_capacities: _Optional[_Iterable[_Union[ServiceCapacity, _Mapping]]] = ..., runtime_version: _Optional[_Union[_common_pb2.VersionId, _Mapping]] = ..., nre_version: _Optional[_Union[_common_pb2.VersionId, _Mapping]] = ..., physics_version: _Optional[_Union[_common_pb2.VersionId, _Mapping]] = ..., driver_version: _Optional[_Union[_common_pb2.VersionId, _Mapping]] = ..., traffic_version: _Optional[_Union[_common_pb2.VersionId, _Mapping]] = ..., video_model_version: _Optional[_Union[_common_pb2.VersionId, _Mapping]] = ...) -> None: ...

class SimulationReturn(_message.Message):
    __slots__ = ("runtime_version", "nre_version", "physics_version", "driver_version", "traffic_version", "rollout_returns", "video_model_version")
    class TimestepMetric(_message.Message):
        __slots__ = ("name", "timestamps_us", "values", "valid", "time_aggregation")
        NAME_FIELD_NUMBER: _ClassVar[int]
        TIMESTAMPS_US_FIELD_NUMBER: _ClassVar[int]
        VALUES_FIELD_NUMBER: _ClassVar[int]
        VALID_FIELD_NUMBER: _ClassVar[int]
        TIME_AGGREGATION_FIELD_NUMBER: _ClassVar[int]
        name: str
        timestamps_us: _containers.RepeatedScalarFieldContainer[int]
        values: _containers.RepeatedScalarFieldContainer[float]
        valid: _containers.RepeatedScalarFieldContainer[bool]
        time_aggregation: TimeAggregation
        def __init__(self, name: _Optional[str] = ..., timestamps_us: _Optional[_Iterable[int]] = ..., values: _Optional[_Iterable[float]] = ..., valid: _Optional[_Iterable[bool]] = ..., time_aggregation: _Optional[_Union[TimeAggregation, str]] = ...) -> None: ...
    class RolloutReturn(_message.Message):
        __slots__ = ("rollout_spec", "success", "rollout_uuid", "error", "timestep_metrics", "aggregated_metrics", "error_code")
        class AggregatedMetricsEntry(_message.Message):
            __slots__ = ("key", "value")
            KEY_FIELD_NUMBER: _ClassVar[int]
            VALUE_FIELD_NUMBER: _ClassVar[int]
            key: str
            value: float
            def __init__(self, key: _Optional[str] = ..., value: _Optional[float] = ...) -> None: ...
        ROLLOUT_SPEC_FIELD_NUMBER: _ClassVar[int]
        SUCCESS_FIELD_NUMBER: _ClassVar[int]
        ROLLOUT_UUID_FIELD_NUMBER: _ClassVar[int]
        ERROR_FIELD_NUMBER: _ClassVar[int]
        TIMESTEP_METRICS_FIELD_NUMBER: _ClassVar[int]
        AGGREGATED_METRICS_FIELD_NUMBER: _ClassVar[int]
        ERROR_CODE_FIELD_NUMBER: _ClassVar[int]
        rollout_spec: RolloutSpec
        success: bool
        rollout_uuid: str
        error: str
        timestep_metrics: _containers.RepeatedCompositeFieldContainer[SimulationReturn.TimestepMetric]
        aggregated_metrics: _containers.ScalarMap[str, float]
        error_code: RolloutErrorCode
        def __init__(self, rollout_spec: _Optional[_Union[RolloutSpec, _Mapping]] = ..., success: bool = ..., rollout_uuid: _Optional[str] = ..., error: _Optional[str] = ..., timestep_metrics: _Optional[_Iterable[_Union[SimulationReturn.TimestepMetric, _Mapping]]] = ..., aggregated_metrics: _Optional[_Mapping[str, float]] = ..., error_code: _Optional[_Union[RolloutErrorCode, str]] = ...) -> None: ...
    RUNTIME_VERSION_FIELD_NUMBER: _ClassVar[int]
    NRE_VERSION_FIELD_NUMBER: _ClassVar[int]
    PHYSICS_VERSION_FIELD_NUMBER: _ClassVar[int]
    DRIVER_VERSION_FIELD_NUMBER: _ClassVar[int]
    TRAFFIC_VERSION_FIELD_NUMBER: _ClassVar[int]
    ROLLOUT_RETURNS_FIELD_NUMBER: _ClassVar[int]
    VIDEO_MODEL_VERSION_FIELD_NUMBER: _ClassVar[int]
    runtime_version: _common_pb2.VersionId
    nre_version: _common_pb2.VersionId
    physics_version: _common_pb2.VersionId
    driver_version: _common_pb2.VersionId
    traffic_version: _common_pb2.VersionId
    rollout_returns: _containers.RepeatedCompositeFieldContainer[SimulationReturn.RolloutReturn]
    video_model_version: _common_pb2.VersionId
    def __init__(self, runtime_version: _Optional[_Union[_common_pb2.VersionId, _Mapping]] = ..., nre_version: _Optional[_Union[_common_pb2.VersionId, _Mapping]] = ..., physics_version: _Optional[_Union[_common_pb2.VersionId, _Mapping]] = ..., driver_version: _Optional[_Union[_common_pb2.VersionId, _Mapping]] = ..., traffic_version: _Optional[_Union[_common_pb2.VersionId, _Mapping]] = ..., rollout_returns: _Optional[_Iterable[_Union[SimulationReturn.RolloutReturn, _Mapping]]] = ..., video_model_version: _Optional[_Union[_common_pb2.VersionId, _Mapping]] = ...) -> None: ...
